version: "3.8"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=0
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - HOST_TMP_FOLDER=/tmp/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-central-1
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  node_application:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - "AWS_HOST=http://localstack:4566"
      - "AWS_ACCESS_KEY_ID=123"
      - "AWS_SECRET_ACCESS_KEY=xyz"
      - "AWS_REGION=eu-central-1"
    ports:
      - "8080:8080"
    depends_on:
      - "localstack"
