version: "3.8"

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack:0.11.5
    network_mode: bridge
    ports:
      - "4566:4566"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - HOST_TMP_FOLDER=/tmp/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  node_application:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - AWS_HOST=http://localstack:4566
      - AWS_ACCESS_KEY_ID=123
      - AWS_SECRET_KEY=xyz
      - AWS_REGION=us-east-1
    network_mode: bridge
    ports:
      - "8080:8080"
